# NumPy Functions
#python/numpy

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


Elements can be accessed by indicating their indices inside square brackets. This works exactly like a simple list.

In [3]:
print(x[1])

2


Arrays are mutable so we can change an individual element by reassigning it.

In [4]:
x[2] = 6
print(x)

[1 2 6 4 5]


We can do this in rank two arrays in exactly the same way, we only need to specify an additional number inside the square brackets.

In [5]:
#Create a rank 2 array
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print_out = 'element at [{}, {}]: {}'
print(print_out.format(0,0,Y[0,0]))
print(print_out.format(2,2,Y[2,2]))
print(print_out.format(1,2,Y[1,2]))

element at [0, 0]: 1
element at [2, 2]: 9
element at [1, 2]: 6


## Deleting Elements

We can delete elements using `np.delete`
This function takes in an array, a list of indices to delete, and an axis to delete from. For rank 1 arrays, the axis keyword is not required. This function returns a new array rather than alters the original array.
For example:


In [16]:
print(x)

[1 2 6 4 5]


In [19]:
np.delete(x, [0,4])
print(x) #still returns original array
x = np.delete(x, [0,4]) #x reassigned as new array with elements deleted.
print(x)

[1 2 6 4 5]
[2 6 4]


With rank 2 arrays, we need to specify the axis to delete. We use 0 to denote a row and 1 to denote a column.

In [25]:
print(Y)
Y2 = np.delete(Y, 0, 0) # deletes first row
print('\n', Y2)
Y3 = np.delete(Y, [0,2], 1) # deletes first and third column
print('\n', Y3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


## Append Function

You can append items to a rank 1 array as follows:

In [28]:
x = np.arange(5)
print(x)

x = np.append(x, 5) # as with delete, append doesn't affect the original array
print(x)

[0 1 2 3 4]
[0 1 2 3 4 5]


You can append multiple items like so:

In [29]:
x = np.append(x, [6,7])
print(x)

[0 1 2 3 4 5 6 7]


For rank 2 arrays:

In [40]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
W = np.append(Y, [[10,11,12]], 0)
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
V = np.append(Y, [[10],[11],[12]], 1)
print(V)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


## Insert Function

Inserts a given list of elements to an array before a given index in a given axis.

In [48]:
x = np.array([1,2,5,6,7])
print(x)

[1 2 5 6 7]


In [49]:
x = np.insert(x, 2, [3,4])
print(x)

[1 2 3 4 5 6 7]


In [51]:
Y = np.array([[1,2,3],[7,8,9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [53]:
W = np.insert(Y,1,[4,5,6],0)
print(W)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
V = np.insert(Y,1,5,1) # inserts column of 5s between column 1 and 2
print(V)

[[1 5 2 3]
 [7 5 8 9]]


## VStack & HStack Function
You can stack arrays on top of each other or side by side by using VStack.

In [66]:
x = np.array([1,2])
print(x)
Y = np.array([[3,4],[5,6]])
print('\n',Y)

[1 2]

 [[3 4]
 [5 6]]


We can stack x on top of Y using VStack:

In [67]:
X = np.vstack((x, Y))
print(X)

[[1 2]
 [3 4]
 [5 6]]


Or stack x on the side of Y like this:

In [68]:
Y = np.hstack((Y, x.reshape(2,1)) ) # x needs to reshaped so that it be stacked on top of Y
print(Y)

[[3 4 1]
 [5 6 2]]
