## Slicing Arrays
#python/numpy

In [1]:
import numpy as np

Slicing is used to access subsets of elements within an array. It is done by combining a colon with indices inside square brackets.

Three types of slicing:
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

Starting index in inclusive and ending index is exclusive.

In [2]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [3]:
z = X[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [4]:
# This can also be achieved like this:
y = X[1:, 2:]
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
# We could grab a subset of the same columns but with the first three rows like so:
w = X[:3, 2:]
print(w)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [6]:
# You can grab an entire row like so:
v = X[:, 2]
print(v)

[ 3  8 13 18]


In [7]:
# or return a rank 2 array of the same row like so:
u = X[:, 2:3]
print(u)

[[ 3]
 [ 8]
 [13]
 [18]]


Slices are not actually a new array that has been assigned to a different variable, they are actually a snapshot of part of the original array; therefore, any changes that are made to the slice are also made to the original array.

In [8]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [10]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [11]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


If you want to create a new array that is a copy of a slice, you use the copy function.

In [12]:
z = np.copy(X[:2,:2])
print(z)

[[1 2]
 [6 7]]


In [13]:
z[0,0] = 100
print(z)

[[100   2]
 [  6   7]]


In [14]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


We can use an array as a list of indices to slice from another:

In [15]:
indices = np.array([1,3])
print(indices)

[1 3]


In [18]:
#Use indices to select the second and fourth row of X
Y = X[indices, :]
print(Y)

[[  6   7   8   9  10]
 [ 16  17  18  19 555]]


In [19]:
#We can also use indices to select the second and fourth column:
W = X[:, indices]
print(W)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


## Other Functions

Diag returns a rank 1 array with the elements from the leading diagonal. It takes the array to return the elements from as its first argument and can take a k value which will translate the values to take frmo the leading diagonal by k.

In [22]:
X = np.arange(9).reshape(3,3)
print(X)

y = np.diag(X)
print('\n',y)

w = np.diag(X, k=1)
print('\n',w)

v = np.diag(X, k=-1)
print('\n',v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [0 4 8]

 [1 5]

 [3 7]


Unique returns a rank 1 array containing all the unique elements from a given array:

In [23]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]
